steps:

- name: node:10.15.1
  entrypoint: yarn
  args: ['install']

- name: node:10.15.1
  entrypoint: npm
  args: ['run', 'build']

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kandula-ui', '.']

images: ['gcr.io/$PROJECT_ID/kandula-ui']


